<a href="https://colab.research.google.com/github/athirach/Learn.py/blob/main/TASK_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [2]:
#please enter your code below this line.
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)
np.sum(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


36

2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [6]:
#please enter your code below this line.
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)
np.sum(x,axis=0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([ 9, 12, 15])

In [5]:
np.sum(x,axis=1)

array([ 3, 12, 21])

3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [11]:
#please enter your code belowthis line.
import numpy as np
x=np.arange(0,16).reshape(4,4)
print(x)
np.max(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


15

In [12]:
np.min(x)

0

In [10]:
np.mean(x)

7.5

4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [27]:
#please enter your code below this line.
import numpy as np
x=np.arange(0,100).reshape(10,10)
print(x)
print(x[6,:])
print(x[3:8,:])
print(x[5,5])
print(x[:,4])
print(x[:,1:5])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[60 61 62 63 64 65 66 67 68 69]
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]]
55
[ 4 14 24 34 44 54 64 74 84 94]
[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]
 [51 52 53 54]
 [61 62 63 64]
 [71 72 73 74]
 [81 82 83 84]
 [91 92 93 94]]
