<a href="https://colab.research.google.com/github/athirach/Learn.py/blob/main/TASK_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a DataFrame by passing a random numpy array,with a datetie index and labelled columns.and display its,
     - Head
     - Tail
     - Index 
     - Columns
     - Values
     - statistics


In [1]:
#please type your answer below this line.
import numpy as np
import pandas as pd
datetie = pd.date_range('2021-08-24',periods=4)
df = pd.DataFrame(np.random.randn(4,4), index=datetie, columns=list('ABCD'))
print("Head:\n", df.head())
print("Tail:\n", df.tail())
print("Index:\n", df.index)
print("Columns:\n", df.columns)
print("Values:\n", df.values)
print("Statistics:\n", df.describe(include='all'))

Head:
                    A         B         C         D
2021-08-24 -1.183632 -0.154680  0.452169 -0.059860
2021-08-25  0.157375 -1.307753 -0.215994  0.482596
2021-08-26 -0.626996  0.466038 -1.610446  0.805716
2021-08-27 -0.726172  0.401999 -1.792099 -0.156421
Tail:
                    A         B         C         D
2021-08-24 -1.183632 -0.154680  0.452169 -0.059860
2021-08-25  0.157375 -1.307753 -0.215994  0.482596
2021-08-26 -0.626996  0.466038 -1.610446  0.805716
2021-08-27 -0.726172  0.401999 -1.792099 -0.156421
Index:
 DatetimeIndex(['2021-08-24', '2021-08-25', '2021-08-26', '2021-08-27'], dtype='datetime64[ns]', freq='D')
Columns:
 Index(['A', 'B', 'C', 'D'], dtype='object')
Values:
 [[-1.18363208 -0.15468018  0.45216935 -0.05986011]
 [ 0.15737464 -1.3077533  -0.21599404  0.48259605]
 [-0.62699638  0.46603771 -1.61044623  0.8057162 ]
 [-0.72617154  0.40199858 -1.79209927 -0.15642092]]
Statistics:
               A         B         C         D
count  4.000000  4.000000  4.000000

2. Use the above table and,
      - find transpose of your data.
      - sort the index in the descending order of the date.

In [2]:
#please provide your answer below this line.
print("Transpose\n", df.transpose())
print("Sorted in Descending Order\n", df.sort_index(ascending=False))

Transpose
    2021-08-24  2021-08-25  2021-08-26  2021-08-27
A   -1.183632    0.157375   -0.626996   -0.726172
B   -0.154680   -1.307753    0.466038    0.401999
C    0.452169   -0.215994   -1.610446   -1.792099
D   -0.059860    0.482596    0.805716   -0.156421
Sorted in Descending Order
                    A         B         C         D
2021-08-27 -0.726172  0.401999 -1.792099 -0.156421
2021-08-26 -0.626996  0.466038 -1.610446  0.805716
2021-08-25  0.157375 -1.307753 -0.215994  0.482596
2021-08-24 -1.183632 -0.154680  0.452169 -0.059860
