<a href="https://colab.research.google.com/github/athirach/Learn.py/blob/main/TASK_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. For the given ndarray b below, evaluate whether elements in array, b are equal to 'red'.Assign the result to b_bool and print the resultant boolean array.
b = np.array(["blue", "blue", "red", "blue"])

In [2]:
#please type your answer below this line.
import numpy as np
b=np.array(["blue","blue","red","blue"])
print(b)
b_bool=b=='red'
print(b_bool)

['blue' 'blue' 'red' 'blue']
[False False  True False]


2. Create two arrays on containing elements from 0-5 and another containing elements from 6-10. Then append this array.

In [4]:
#please type your answer below this line.
import numpy as np
x=np.arange(0,6)
y=np.arange(6,11)
print(np.append(x,y))

[ 0  1  2  3  4  5  6  7  8  9 10]


3. Create a 2x4 array containing values from 0-7 and another 2x4 containing values from 8-15. Now append this with,

  a) axis as 0

  b) axis as 1

In [7]:
#please type your answer below this line.
import numpy as np
x=np.arange(0,8).reshape(2,4)
y=np.arange(8,16).reshape(2,4)
print(x)
print(y)
print(np.append(x,y,axis=0))
print(np.append(x,y,axis=1))

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]
